apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id | dump}}
  description: ${{values.description | dump}}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
    'github.com/project-slug': winecombr/${{values.destination.repo | dump}}
    'backstage.io/kubernetes-id': ${{values.component_id | dump}}
    'github.com/project-readme-path': 'packages/sub-module/README.md' # como default, ele porcura na raiz do repositório. é possível definir uma caminho com essas annotations
    'google.com/cloudbuild-project-slug': [your-project-slug]
spec:
  type: service
  lifecycle: production
  owner: ${{values.owner | dump}}



apiVersion: 'backstage.io/v1alpha1'
kind: Component
metadata:
  name: '{{ parameters.component_id }}'
  description: '{{ parameters.description }}'
  annotations:
    team: '{{ parameters.team }}'
    repoId: '{{ steps.createRepo.output.id }}'
    technical_lead: '{{ parameters.technical_lead }}'
    product_owner: '{{ parameters.product_owner }}'
    monitoring_apm: '{{ parameters.new_relic_apm_enabled }}'
    gitlab.com/project-slug: '{{ projectSlug parameters.repoUrl }}'
    jira/project-key: CCMR
    jira/application-name: '{{ parameters.country }}-{{ parameters.application_name }}'
  tags:
    - aws
    - service
    - kubernetes
    - java
    - springboot
spec:
  type: service
  lifecycle: '{{ parameters.lifecycle }}'
  owner: '{{ parameters.team }}'