{{- if .Values.istio.enabled }}
{{- if .Values.canaryDeployment.enabled }}
{{- if .Values.canaryDeployment.hpa.enabled }}
{{- $fullName := include "helpers.fullname" . -}}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $fullName }}-canary
  labels:
    {{- include "helpers.labels" . | nindent 4 }}
    canary: "true"
spec:
  minReplicas: {{ .Values.canaryDeployment.hpa.minReplicas }}
  maxReplicas: {{ .Values.canaryDeployment.hpa.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ .Values.kind }}
    name: {{ $fullName }}-canary
  metrics:
  {{- with .Values.canaryDeployment.hpa.custom }}
    {{- toYaml . | nindent 4 }}
  {{- end -}}

  {{- with .Values.canaryDeployment.hpa.targetCpu }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ . }}
  {{- end -}}
{{- end }}
{{- end }}
{{- end }}