{{- if .Values.productionDeployment.hpa.enabled -}}
{{- $fullName := include "helpers.fullname" . -}}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "helpers.labels" . | nindent 4 }}
    canary: "false"
spec:
  minReplicas: {{ .Values.productionDeployment.hpa.minReplicas }}
  maxReplicas: {{ .Values.productionDeployment.hpa.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ .Values.kind }}
    name: {{ $fullName }}
  metrics:
  {{- with .Values.productionDeployment.hpa.custom }}
    {{- toYaml . | nindent 4 }}
  {{- end -}}

  {{- with .Values.productionDeployment.hpa.targetCpu }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ . }}
  {{- end -}}
{{- end }}