{{ if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "helpers.fullname" . }}
  labels:
    app: applepay-service
    {{- include "helpers.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{ if .Values.ingress.class }}
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    {{ end }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  rules:
    {{- range $i, $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "helpers.fullname" $ }}
              servicePort: 80
    {{ end -}}
{{ end }}