{{- if .Values.istio.enabled }}
{{- if .Values.canaryDeployment.enabled }}
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "helpers.fullname" . }}-canary
  labels:
    {{- include "helpers.labels" . | nindent 4 }}
    canary: "true"
spec:
  maxUnavailable: {{ .Values.canaryDeployment.pdb.maxUnavailable }}
  minAvailable: {{ .Values.canaryDeployment.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "helpers.selector" . | nindent 6 }}
      canary: "true"
{{- end }}
{{- end }}