## Builds wine-search-products-indexer and wine-search-products-search-engine
## Requires the following variable to be set:
##   - _SOURCE_ENV: the name of the enviroment, e.g: staging, production ...
##   - _PROJECTS: name of the projects that should be built (dependencies are built automatically).
logsBucket: gs://winecombr-ci-cd-logs

substitutions:
  ## The bucket must be created manually
  _CACHE_BUCKET: winecombr-ci-cd-cache
  _MAVEN_IMAGE: maven:3.6.3-openjdk-${{values.javaVersion}}

options:
  env:
    - "CI=true"
    - "REPOSITORY=gcr.io"
    - "PROJECT_ID=$PROJECT_ID"
    - "COMMIT_SHA=$COMMIT_SHA"
    - "BRANCH_NAME=$BRANCH_NAME"
    - "SOURCE_ENV=$_SOURCE_ENV"

steps:

  - name: ${_MAVEN_IMAGE}
    id: build
    waitFor: ["restore_cache"]
    entrypoint: sh
    args:
      - -c
      - "mvn clean package \
        --file=./pom.xml \
        jib:build \
        --also-make \ 
        --threads=1C \
        -Djib.container.creationTime=USE_CURRENT_TIMESTAMP \
        -Djib.to.tags=$SHORT_SHA-$(date +%s),$COMMIT_SHA \
        -Dmaven.test.skip=true \
        -Dmaven.repo.local=.maven"

  - name: "gcr.io/$PROJECT_ID/save_cache"
    id: save_cache
    waitFor: ["build"]
    args:
      - "--bucket=gs://${_CACHE_BUCKET}/$REPO_NAME/"
      - "--key=${BRANCH_NAME}"
      - "--path=.maven"
